# INSTRUCTION:
# Build image (from the directory containing dockerfile):
# docker build -f dockerfile --tag 'ubuntu-g4:22.04-11.1.3-plgrid' .
# Run container:
# docker run -ti --rm ubuntu-g4:22.04-11.1.3-plgrid /bin/bash

FROM ubuntu-22.04-root-6.32.02-g4-11.2.2:v1r2

ARG JPET_G4_BRANCH=develop-agh-thashtable-issue

# ----------------------------------------
# Clone the repository (cached unless branch changes)
RUN cd /opt && git clone --single-branch --branch $JPET_G4_BRANCH \
    https://github.com/JPETTomography/J-PET-geant4.git

RUN /bin/bash -c "\
    source /opt/conda/etc/profile.d/conda.sh && \
    conda activate jpet && \
    cd /opt/J-PET-geant4 && ./setups/init_submodules.sh && \
    mkdir -p build && cd build && \
    cmake ../ -DMT=ON && make -j2"